<a href="https://colab.research.google.com/github/Siva6933/Matrix-Operations-Tool/blob/main/Matrix_Operations_Tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy


In [ ]:
import numpy as np

def input_matrix(name="Matrix"):
    rows = int(input(f"Enter number of rows for {name}: "))
    cols = int(input(f"Enter number of columns for {name}: "))
    print(f"Enter elements row by row for {name}:")
    matrix = []
    for i in range(rows):
        row = list(map(float, input(f"Row {i+1}: ").split()))
        if len(row) != cols:
            print("Error: Number of elements must match columns.")
            return input_matrix(name)
        matrix.append(row)
    return np.array(matrix)

def display_matrix(matrix, name="Result"):
    print(f"\n{name}:\n{matrix}\n")

def main():
    print("=== Matrix Operations Tool ===")
    print("Operations available:")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Transpose")
    print("5. Determinant")
    print("6. Exit")

    while True:
        choice = input("\nEnter your choice (1-6): ")

        if choice == '1':
            A = input_matrix("Matrix A")
            B = input_matrix("Matrix B")
            if A.shape == B.shape:
                display_matrix(A + B, "A + B")
            else:
                print("Error: Matrices must be of same dimension for addition.")

        elif choice == '2':
            A = input_matrix("Matrix A")
            B = input_matrix("Matrix B")
            if A.shape == B.shape:
                display_matrix(A - B, "A - B")
            else:
                print("Error: Matrices must be of same dimension for subtraction.")

        elif choice == '3':
            A = input_matrix("Matrix A")
            B = input_matrix("Matrix B")
            if A.shape[1] == B.shape[0]:
                display_matrix(np.matmul(A, B), "A x B")
            else:
                print("Error: Columns of A must match rows of B for multiplication.")

        elif choice == '4':
            A = input_matrix("Matrix")
            display_matrix(A.T, "Transpose")

        elif choice == '5':
            A = input_matrix("Matrix")
            if A.shape[0] == A.shape[1]:
                display_matrix(np.linalg.det(A), "Determinant")
            else:
                print("Error: Determinant is only defined for square matrices.")

        elif choice == '6':
            print("Exiting Matrix Operations Tool. Goodbye!")
            break

        else:
            print("Invalid choice. Please enter a number between 1 and 6.")

if __name__ == "__main__":
    main()


=== Matrix Operations Tool ===
Operations available:
1. Addition
2. Subtraction
3. Multiplication
4. Transpose
5. Determinant
6. Exit

Enter your choice (1-6): 1
Enter number of rows for Matrix A: 3
Enter number of columns for Matrix A: 3
Enter elements row by row for Matrix A:
Row 1: 5 3 2
Row 2: 2 4 6
Row 3: 1 4 7
Enter number of rows for Matrix B: 2
Enter number of columns for Matrix B: 2
Enter elements row by row for Matrix B:
Row 1: 1 5 
Row 2: 4 9
Error: Matrices must be of same dimension for addition.

Enter your choice (1-6): 1
Enter number of rows for Matrix A: 3
Enter number of columns for Matrix A: 3
Enter elements row by row for Matrix A:
Row 1: 5 3 2
Row 2: 2 4 6
Row 3: 1 4 7
Enter number of rows for Matrix B: 3
Enter number of columns for Matrix B: 3
Enter elements row by row for Matrix B:
Row 1: 1 5 8
Row 2: 4 9 10
Row 3: 15 3 6

A + B:
[[ 6.  8. 10.]
 [ 6. 13. 16.]
 [16.  7. 13.]]


Enter your choice (1-6): 5
Enter number of rows for Matrix: 3
Enter number of columns fo

In [ ]:
import numpy as np

def input_matrix(name="Matrix"):
    rows = int(input(f"Enter number of rows for {name}: "))
    cols = int(input(f"Enter number of columns for {name}: "))
    print(f"Enter elements row by row for {name}:")
    matrix = []
    for i in range(rows):
        row = list(map(float, input(f"Row {i+1}: ").split()))
        if len(row) != cols:
            print("Error: Number of elements must match columns.")
            return input_matrix(name)
        matrix.append(row)
    return np.array(matrix)

def display_matrix(matrix, name="Result"):
    print(f"\n{name}:\n{matrix}\n")

def main():
    print("=== Matrix Operations Tool ===")
    print("Operations available:")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Transpose")
    print("5. Determinant")
    print("6. Exit")

    while True:
        choice = input("\nEnter your choice (1-6): ")

        if choice == '1':
            A = input_matrix("Matrix A")
            B = input_matrix("Matrix B")
            if A.shape == B.shape:
                display_matrix(A + B, "A + B")
            else:
                print("Error: Matrices must be of same dimension for addition.")

        elif choice == '2':
            A = input_matrix("Matrix A")
            B = input_matrix("Matrix B")
            if A.shape == B.shape:
                display_matrix(A - B, "A - B")
            else:
                print("Error: Matrices must be of same dimension for subtraction.")

        elif choice == '3':
            A = input_matrix("Matrix A")
            B = input_matrix("Matrix B")
            if A.shape[1] == B.shape[0]:
                display_matrix(np.matmul(A, B), "A x B")
            else:
                print("Error: Columns of A must match rows of B for multiplication.")

        elif choice == '4':
            A = input_matrix("Matrix")
            display_matrix(A.T, "Transpose")

        elif choice == '5':
            A = input_matrix("Matrix")
            if A.shape[0] == A.shape[1]:
                display_matrix(np.linalg.det(A), "Determinant")
            else:
                print("Error: Determinant is only defined for square matrices.")

        elif choice == '6':
            print("Exiting Matrix Operations Tool. Goodbye!")
            break

        else:
            print("Invalid choice. Please enter a number between 1 and 6.")

if __name__ == "__main__":
    main()



=== Matrix Operations Tool ===
Operations available:
1. Addition
2. Subtraction
3. Multiplication
4. Transpose
5. Determinant
6. Exit

Enter your choice (1-6): 5
Enter number of rows for Matrix: 4
Enter number of columns for Matrix: 4
Enter elements row by row for Matrix:
Row 1: 1 2 3 4
Row 2: 2 3 4 5
Row 3: 3 4 5 6
Row 4: 4 5 6 7

Determinant:
0.0


Enter your choice (1-6): 6
Exiting Matrix Operations Tool. Goodbye!
